### ISSUE TITLE
Component level theming

### ISSUE THREAD

**Issue by azrijamil** [bootstrap-styled/v4#109]
How to override a theme variable on component level? Such as `$btn-primary-bg` for single Button component only. Currently I'm doing as follow to change the button color individually.

```jsx
const ButtonFb = styled(Button)`
  background: #3C5A99 !important;
`;
```

**Comment by kopax** [comment]
Hi @azrijamil.

There's nothing wrong with your method.

This is how styled work for [extending styles](https://www.styled-components.com/docs/basics#extending-styles).

You want to use one of the bootstrap colors, otherwise, you'll have to create your own variable(s) for that `<Button />`, it can be done by using `makeTheme`.

In general, this is how I do the application side when I need more customization for a particular button.

Another way around is possible because it uses styled-component, you can also pass `props.theme` directly to the `<Button />`, if you go that way, there is no shallow merge and you'll have to set all the variables used by the button.

Perhaps more details about what you are doing will help us give us our best experience for what you are doing.

**Comment by azrijamil** [comment]
Thanks for the very brief information on this matter, and noted on the shallow merge on passing directly the `theme` props to component. In fact using double `&` is a very elegance solution. Big Thanks @kopax for the guide.

**Comment by kopax** [comment]
You are welcome, If you do like that project, to help us boost engagment you are welcome to star our repository.
